CREATE DATABASE DATA;
USE DATA;
DROP TABLE IF EXISTS `user`;
CREATE TABLE USER(
	`u_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	`account` VARCHAR(128) CHARACTER SET utf8 NOT NULL COMMENT '账号',
	`password` VARCHAR(128) CHARACTER SET utf8 NOT NULL COMMENT '密码',
	PRIMARY KEY (`u_id`)
)ENGINE = INNODB DEFAULT CHARACTER SET = utf8;

SELECT * FROM USER;
INSERT USER VALUES(NULL,"123","123");